In [124]:
import pandas as pd
import numpy as np

In [125]:
import pandas as pd

# Professional E-commerce Data with added "human error"
orders_data = {
    "OrderID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125],
    "CustomerID": ["C-1", "C-2", "C-3", "C-1", "C-4", "C-5", "C-2", "C-6", "C-7", "C-8", "C-9", "C-10", "C-1", "C-11", "C-12", "C-13", "C-14", "C-15", "C-16", "C-17", "C-18", "C-19", "C-20", "C-21", "C-22"],
    "Product": ["Ceramic Mug", "Cotton Socks", "Mechanical Keyboard", "Ballpoint Pens", "Desk Lamp", "Honey Jar", "Yoga Mat", "USB-C Hub", "Water Bottle", "Scented Candle", "Tote Bag", "Stapler", "Coffee Beans", "Desk Organizer", "AA Batteries", "Hand Cream", "Phone Stand", "Oversized Hoodie", "27-inch Monitor", "Tea Infuser", "Microfiber Cloth", "Sunglasses", "Succulent", "Bluetooth Speaker", "Mouse Pad"],
    "Category": ["Kitchen", "Apparel", "Electronics", "Stationery", "Office", "Pantry", "Fitness", "Electronics", "Housewares", "Home", "Accessories", "Office", "Pantry", "Office", "Electronics", "Beauty", "Electronics", "Apparel", None, "Kitchen", "Housewares", "Accessories", "Home", "Electronics", "Electronics"],
    "Quantity": [2, 3, 1, 5, 1, 1, 1, None, 1, 2, 1, 1, 2, 1, 4, 1, 1, 1, 1, 2, 5, 1, 3, 1, 1],
    "Price": [12.50, 9.00, 120.00, 4.50, 35.00, 14.00, 20.00, 45.00, 15.00, 12.00, 10.00, 8.50, 18.00, 22.00, 15.99, 9.50, None, 45.00, None, 6.50, 12.00, 18.00, 12.00, 89.00, 15.00],
    "OrderDate": ["2023-01-15", "2023-02-10", "2023-06-05", "2023-04-20", "2023-05-12", "2023-07-18", "2023-08-22", "2023-12-01", "2023-11-15", "2023-12-05", "2024-01-12", "2024-02-28", "2024-03-15", "2024-04-01", "2024-04-22", "2024-05-30", "2024-07-04", "2024-08-14", "2024-09-19", "2024-10-05", "2024-11-11", "2024-11-28", "2024-12-05", "2024-12-20", "2024-12-30"],
    "Rating": [5, 4, 5, 3, 5, 5, 4, None, 5, 4, 5, 4, 5, 4, 5, 5, 3, 5, 4, 5, 4, 2, 5, None, 5],
    "Review": ["Great", "Comfy", None, "Skips", "Bright", "Sweet", "Good", None, "Fine", "Nice", "Strong", "Staples well", "Fresh", "Clean", "Long life", "Smooth", "Steady", "Warm", "None", "Simple", "Soft", "Dark", "Green", "Loud", "Smooth"]
}

df = pd.DataFrame(orders_data)

In [126]:
# Q1: Create a DataFrame with the following e-commerce sales data:
# Columns: OrderID, CustomerID, Product, Category, Quantity, Price, OrderDate, Rating, Review
# Create at least 50 sample records with realistic data including dates from 2023-2024
# Display the first 10 and last 5 records using head() and tail()

df = pd.DataFrame(orders_data)
df.head(10)

OrderID CustomerID              Product     Category  Quantity  Price  \
0      101        C-1          Ceramic Mug      Kitchen       2.0   12.5   
1      102        C-2         Cotton Socks      Apparel       3.0    9.0   
2      103        C-3  Mechanical Keyboard  Electronics       1.0  120.0   
3      104        C-1       Ballpoint Pens   Stationery       5.0    4.5   
4      105        C-4            Desk Lamp       Office       1.0   35.0   
5      106        C-5            Honey Jar       Pantry       1.0   14.0   
6      107        C-2             Yoga Mat      Fitness       1.0   20.0   
7      108        C-6            USB-C Hub  Electronics       NaN   45.0   
8      109        C-7         Water Bottle   Housewares       1.0   15.0   
9      110        C-8       Scented Candle         Home       2.0   12.0   

    OrderDate  Rating  Review  
0  2023-01-15     5.0   Great  
1  2023-02-10     4.0   Comfy  
2  2023-06-05     5.0    None  
3  2023-04-20     3.0   Skips  
4  2023-05-12     5.0  Bright  
5  2023-07-18     5.0   Sweet  
6  2023-08-22     4.0    Good  
7  2023-12-01     NaN    None  
8  2023-11-15     5.0    Fine  
9  2023-12-05     4.0    Nice

In [127]:
df.tail(5)

OrderID CustomerID            Product     Category  Quantity  Price  \
20      121       C-18   Microfiber Cloth   Housewares       5.0   12.0   
21      122       C-19         Sunglasses  Accessories       1.0   18.0   
22      123       C-20          Succulent         Home       3.0   12.0   
23      124       C-21  Bluetooth Speaker  Electronics       1.0   89.0   
24      125       C-22          Mouse Pad  Electronics       1.0   15.0   

     OrderDate  Rating  Review  
20  2024-11-11     4.0    Soft  
21  2024-11-28     2.0    Dark  
22  2024-12-05     5.0   Green  
23  2024-12-20     NaN    Loud  
24  2024-12-30     5.0  Smooth

In [128]:
# Q2: Use info() and describe() to get a comprehensive overview of the dataset
# Identify data types, missing values, and statistical summary
# Print the column names using columns attribute and shape of the dataset
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   OrderID     25 non-null     int64  
 1   CustomerID  25 non-null     object 
 2   Product     25 non-null     object 
 3   Category    24 non-null     object 
 4   Quantity    24 non-null     float64
 5   Price       23 non-null     float64
 6   OrderDate   25 non-null     object 
 7   Rating      23 non-null     float64
 8   Review      23 non-null     object 
dtypes: float64(3), int64(1), object(5)
memory usage: 1.9+ KB
None


In [129]:
print(df.isnull().sum())

OrderID       0
CustomerID    0
Product       0
Category      1
Quantity      1
Price         2
OrderDate     0
Rating        2
Review        2
dtype: int64


In [130]:
print(df.describe())

          OrderID   Quantity       Price     Rating
count   25.000000  24.000000   23.000000  23.000000
mean   113.000000   1.791667   24.716957   4.391304
std      7.359801   1.284664   27.775551   0.838783
min    101.000000   1.000000    4.500000   2.000000
25%    107.000000   1.000000   11.000000   4.000000
50%    113.000000   1.000000   15.000000   5.000000
75%    119.000000   2.000000   21.000000   5.000000
max    125.000000   5.000000  120.000000   5.000000


In [131]:
print("Shape of Dataset: ",df.shape)
print("Columns: ", df.columns)

Shape of Dataset:  (25, 9)
Columns:  Index(['OrderID', 'CustomerID', 'Product', 'Category', 'Quantity', 'Price',
       'OrderDate', 'Rating', 'Review'],
      dtype='object')


In [132]:
# Q3: Introduce 10% missing values randomly in Rating and Review columns
# Detect missing values and display the count of missing values per column
# Fill missing ratings with the median rating and missing reviews with "No review provided"

print(df.isnull().sum())

OrderID       0
CustomerID    0
Product       0
Category      1
Quantity      1
Price         2
OrderDate     0
Rating        2
Review        2
dtype: int64


In [133]:
df['Rating'].fillna(df['Rating'].median(), inplace = True)
df

C:\Users\harsh\AppData\Local\Temp\ipykernel_29944\288563309.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Rating'].fillna(df['Rating'].median(), inplace = True)


OrderID CustomerID              Product     Category  Quantity   Price  \
0       101        C-1          Ceramic Mug      Kitchen       2.0   12.50   
1       102        C-2         Cotton Socks      Apparel       3.0    9.00   
2       103        C-3  Mechanical Keyboard  Electronics       1.0  120.00   
3       104        C-1       Ballpoint Pens   Stationery       5.0    4.50   
4       105        C-4            Desk Lamp       Office       1.0   35.00   
5       106        C-5            Honey Jar       Pantry       1.0   14.00   
6       107        C-2             Yoga Mat      Fitness       1.0   20.00   
7       108        C-6            USB-C Hub  Electronics       NaN   45.00   
8       109        C-7         Water Bottle   Housewares       1.0   15.00   
9       110        C-8       Scented Candle         Home       2.0   12.00   
10      111        C-9             Tote Bag  Accessories       1.0   10.00   
11      112       C-10              Stapler       Office       1.0    8.50   
12      113        C-1         Coffee Beans       Pantry       2.0   18.00   
13      114       C-11       Desk Organizer       Office       1.0   22.00   
14      115       C-12         AA Batteries  Electronics       4.0   15.99   
15      116       C-13           Hand Cream       Beauty       1.0    9.50   
16      117       C-14          Phone Stand  Electronics       1.0     NaN   
17      118       C-15     Oversized Hoodie      Apparel       1.0   45.00   
18      119       C-16      27-inch Monitor         None       1.0     NaN   
19      120       C-17          Tea Infuser      Kitchen       2.0    6.50   
20      121       C-18     Microfiber Cloth   Housewares       5.0   12.00   
21      122       C-19           Sunglasses  Accessories       1.0   18.00   
22      123       C-20            Succulent         Home       3.0   12.00   
23      124       C-21    Bluetooth Speaker  Electronics       1.0   89.00   
24      125       C-22            Mouse Pad  Electronics       1.0   15.00   

     OrderDate  Rating        Review  
0   2023-01-15     5.0         Great  
1   2023-02-10     4.0         Comfy  
2   2023-06-05     5.0          None  
3   2023-04-20     3.0         Skips  
4   2023-05-12     5.0        Bright  
5   2023-07-18     5.0         Sweet  
6   2023-08-22     4.0          Good  
7   2023-12-01     5.0          None  
8   2023-11-15     5.0          Fine  
9   2023-12-05     4.0          Nice  
10  2024-01-12     5.0        Strong  
11  2024-02-28     4.0  Staples well  
12  2024-03-15     5.0         Fresh  
13  2024-04-01     4.0         Clean  
14  2024-04-22     5.0     Long life  
15  2024-05-30     5.0        Smooth  
16  2024-07-04     3.0        Steady  
17  2024-08-14     5.0          Warm  
18  2024-09-19     4.0          None  
19  2024-10-05     5.0        Simple  
20  2024-11-11     4.0          Soft  
21  2024-11-28     2.0          Dark  
22  2024-12-05     5.0         Green  
23  2024-12-20     5.0          Loud  
24  2024-12-30     5.0        Smooth

In [134]:
df['Review'] = df['Review'].fillna("No review provided")
df

OrderID CustomerID              Product     Category  Quantity   Price  \
0       101        C-1          Ceramic Mug      Kitchen       2.0   12.50   
1       102        C-2         Cotton Socks      Apparel       3.0    9.00   
2       103        C-3  Mechanical Keyboard  Electronics       1.0  120.00   
3       104        C-1       Ballpoint Pens   Stationery       5.0    4.50   
4       105        C-4            Desk Lamp       Office       1.0   35.00   
5       106        C-5            Honey Jar       Pantry       1.0   14.00   
6       107        C-2             Yoga Mat      Fitness       1.0   20.00   
7       108        C-6            USB-C Hub  Electronics       NaN   45.00   
8       109        C-7         Water Bottle   Housewares       1.0   15.00   
9       110        C-8       Scented Candle         Home       2.0   12.00   
10      111        C-9             Tote Bag  Accessories       1.0   10.00   
11      112       C-10              Stapler       Office       1.0    8.50   
12      113        C-1         Coffee Beans       Pantry       2.0   18.00   
13      114       C-11       Desk Organizer       Office       1.0   22.00   
14      115       C-12         AA Batteries  Electronics       4.0   15.99   
15      116       C-13           Hand Cream       Beauty       1.0    9.50   
16      117       C-14          Phone Stand  Electronics       1.0     NaN   
17      118       C-15     Oversized Hoodie      Apparel       1.0   45.00   
18      119       C-16      27-inch Monitor         None       1.0     NaN   
19      120       C-17          Tea Infuser      Kitchen       2.0    6.50   
20      121       C-18     Microfiber Cloth   Housewares       5.0   12.00   
21      122       C-19           Sunglasses  Accessories       1.0   18.00   
22      123       C-20            Succulent         Home       3.0   12.00   
23      124       C-21    Bluetooth Speaker  Electronics       1.0   89.00   
24      125       C-22            Mouse Pad  Electronics       1.0   15.00   

     OrderDate  Rating              Review  
0   2023-01-15     5.0               Great  
1   2023-02-10     4.0               Comfy  
2   2023-06-05     5.0  No review provided  
3   2023-04-20     3.0               Skips  
4   2023-05-12     5.0              Bright  
5   2023-07-18     5.0               Sweet  
6   2023-08-22     4.0                Good  
7   2023-12-01     5.0  No review provided  
8   2023-11-15     5.0                Fine  
9   2023-12-05     4.0                Nice  
10  2024-01-12     5.0              Strong  
11  2024-02-28     4.0        Staples well  
12  2024-03-15     5.0               Fresh  
13  2024-04-01     4.0               Clean  
14  2024-04-22     5.0           Long life  
15  2024-05-30     5.0              Smooth  
16  2024-07-04     3.0              Steady  
17  2024-08-14     5.0                Warm  
18  2024-09-19     4.0                None  
19  2024-10-05     5.0              Simple  
20  2024-11-11     4.0                Soft  
21  2024-11-28     2.0                Dark  
22  2024-12-05     5.0               Green  
23  2024-12-20     5.0                Loud  
24  2024-12-30     5.0              Smooth

In [135]:
# Q4: Create a new column 'TotalAmount' by multiplying Quantity and Price
# Add another column 'DiscountedPrice' that applies 10% discount on orders above $20
# Use conditional selection to filter orders where TotalAmount > $25

df['TotalAmount'] = df['Quantity']*df['Price']
df

OrderID CustomerID              Product     Category  Quantity   Price  \
0       101        C-1          Ceramic Mug      Kitchen       2.0   12.50   
1       102        C-2         Cotton Socks      Apparel       3.0    9.00   
2       103        C-3  Mechanical Keyboard  Electronics       1.0  120.00   
3       104        C-1       Ballpoint Pens   Stationery       5.0    4.50   
4       105        C-4            Desk Lamp       Office       1.0   35.00   
5       106        C-5            Honey Jar       Pantry       1.0   14.00   
6       107        C-2             Yoga Mat      Fitness       1.0   20.00   
7       108        C-6            USB-C Hub  Electronics       NaN   45.00   
8       109        C-7         Water Bottle   Housewares       1.0   15.00   
9       110        C-8       Scented Candle         Home       2.0   12.00   
10      111        C-9             Tote Bag  Accessories       1.0   10.00   
11      112       C-10              Stapler       Office       1.0    8.50   
12      113        C-1         Coffee Beans       Pantry       2.0   18.00   
13      114       C-11       Desk Organizer       Office       1.0   22.00   
14      115       C-12         AA Batteries  Electronics       4.0   15.99   
15      116       C-13           Hand Cream       Beauty       1.0    9.50   
16      117       C-14          Phone Stand  Electronics       1.0     NaN   
17      118       C-15     Oversized Hoodie      Apparel       1.0   45.00   
18      119       C-16      27-inch Monitor         None       1.0     NaN   
19      120       C-17          Tea Infuser      Kitchen       2.0    6.50   
20      121       C-18     Microfiber Cloth   Housewares       5.0   12.00   
21      122       C-19           Sunglasses  Accessories       1.0   18.00   
22      123       C-20            Succulent         Home       3.0   12.00   
23      124       C-21    Bluetooth Speaker  Electronics       1.0   89.00   
24      125       C-22            Mouse Pad  Electronics       1.0   15.00   

     OrderDate  Rating              Review  TotalAmount  
0   2023-01-15     5.0               Great        25.00  
1   2023-02-10     4.0               Comfy        27.00  
2   2023-06-05     5.0  No review provided       120.00  
3   2023-04-20     3.0               Skips        22.50  
4   2023-05-12     5.0              Bright        35.00  
5   2023-07-18     5.0               Sweet        14.00  
6   2023-08-22     4.0                Good        20.00  
7   2023-12-01     5.0  No review provided          NaN  
8   2023-11-15     5.0                Fine        15.00  
9   2023-12-05     4.0                Nice        24.00  
10  2024-01-12     5.0              Strong        10.00  
11  2024-02-28     4.0        Staples well         8.50  
12  2024-03-15     5.0               Fresh        36.00  
13  2024-04-01     4.0               Clean        22.00  
14  2024-04-22     5.0           Long life        63.96  
15  2024-05-30     5.0              Smooth         9.50  
16  2024-07-04     3.0              Steady          NaN  
17  2024-08-14     5.0                Warm        45.00  
18  2024-09-19     4.0                None          NaN  
19  2024-10-05     5.0              Simple        13.00  
20  2024-11-11     4.0                Soft        60.00  
21  2024-11-28     2.0                Dark        18.00  
22  2024-12-05     5.0               Green        36.00  
23  2024-12-20     5.0                Loud        89.00  
24  2024-12-30     5.0              Smooth        15.00

In [136]:
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].median())
df['Price'] = df['Price'].fillna(df['Price'].mean())
df

OrderID CustomerID              Product     Category  Quantity  \
0       101        C-1          Ceramic Mug      Kitchen       2.0   
1       102        C-2         Cotton Socks      Apparel       3.0   
2       103        C-3  Mechanical Keyboard  Electronics       1.0   
3       104        C-1       Ballpoint Pens   Stationery       5.0   
4       105        C-4            Desk Lamp       Office       1.0   
5       106        C-5            Honey Jar       Pantry       1.0   
6       107        C-2             Yoga Mat      Fitness       1.0   
7       108        C-6            USB-C Hub  Electronics       1.0   
8       109        C-7         Water Bottle   Housewares       1.0   
9       110        C-8       Scented Candle         Home       2.0   
10      111        C-9             Tote Bag  Accessories       1.0   
11      112       C-10              Stapler       Office       1.0   
12      113        C-1         Coffee Beans       Pantry       2.0   
13      114       C-11       Desk Organizer       Office       1.0   
14      115       C-12         AA Batteries  Electronics       4.0   
15      116       C-13           Hand Cream       Beauty       1.0   
16      117       C-14          Phone Stand  Electronics       1.0   
17      118       C-15     Oversized Hoodie      Apparel       1.0   
18      119       C-16      27-inch Monitor         None       1.0   
19      120       C-17          Tea Infuser      Kitchen       2.0   
20      121       C-18     Microfiber Cloth   Housewares       5.0   
21      122       C-19           Sunglasses  Accessories       1.0   
22      123       C-20            Succulent         Home       3.0   
23      124       C-21    Bluetooth Speaker  Electronics       1.0   
24      125       C-22            Mouse Pad  Electronics       1.0   

         Price   OrderDate  Rating              Review  TotalAmount  
0    12.500000  2023-01-15     5.0               Great        25.00  
1     9.000000  2023-02-10     4.0               Comfy        27.00  
2   120.000000  2023-06-05     5.0  No review provided       120.00  
3     4.500000  2023-04-20     3.0               Skips        22.50  
4    35.000000  2023-05-12     5.0              Bright        35.00  
5    14.000000  2023-07-18     5.0               Sweet        14.00  
6    20.000000  2023-08-22     4.0                Good        20.00  
7    45.000000  2023-12-01     5.0  No review provided          NaN  
8    15.000000  2023-11-15     5.0                Fine        15.00  
9    12.000000  2023-12-05     4.0                Nice        24.00  
10   10.000000  2024-01-12     5.0              Strong        10.00  
11    8.500000  2024-02-28     4.0        Staples well         8.50  
12   18.000000  2024-03-15     5.0               Fresh        36.00  
13   22.000000  2024-04-01     4.0               Clean        22.00  
14   15.990000  2024-04-22     5.0           Long life        63.96  
15    9.500000  2024-05-30     5.0              Smooth         9.50  
16   24.716957  2024-07-04     3.0              Steady          NaN  
17   45.000000  2024-08-14     5.0                Warm        45.00  
18   24.716957  2024-09-19     4.0                None          NaN  
19    6.500000  2024-10-05     5.0              Simple        13.00  
20   12.000000  2024-11-11     4.0                Soft        60.00  
21   18.000000  2024-11-28     2.0                Dark        18.00  
22   12.000000  2024-12-05     5.0               Green        36.00  
23   89.000000  2024-12-20     5.0                Loud        89.00  
24   15.000000  2024-12-30     5.0              Smooth        15.00

In [137]:
df['TotalAmount'] = df['Quantity']*df['Price']
df

OrderID CustomerID              Product     Category  Quantity  \
0       101        C-1          Ceramic Mug      Kitchen       2.0   
1       102        C-2         Cotton Socks      Apparel       3.0   
2       103        C-3  Mechanical Keyboard  Electronics       1.0   
3       104        C-1       Ballpoint Pens   Stationery       5.0   
4       105        C-4            Desk Lamp       Office       1.0   
5       106        C-5            Honey Jar       Pantry       1.0   
6       107        C-2             Yoga Mat      Fitness       1.0   
7       108        C-6            USB-C Hub  Electronics       1.0   
8       109        C-7         Water Bottle   Housewares       1.0   
9       110        C-8       Scented Candle         Home       2.0   
10      111        C-9             Tote Bag  Accessories       1.0   
11      112       C-10              Stapler       Office       1.0   
12      113        C-1         Coffee Beans       Pantry       2.0   
13      114       C-11       Desk Organizer       Office       1.0   
14      115       C-12         AA Batteries  Electronics       4.0   
15      116       C-13           Hand Cream       Beauty       1.0   
16      117       C-14          Phone Stand  Electronics       1.0   
17      118       C-15     Oversized Hoodie      Apparel       1.0   
18      119       C-16      27-inch Monitor         None       1.0   
19      120       C-17          Tea Infuser      Kitchen       2.0   
20      121       C-18     Microfiber Cloth   Housewares       5.0   
21      122       C-19           Sunglasses  Accessories       1.0   
22      123       C-20            Succulent         Home       3.0   
23      124       C-21    Bluetooth Speaker  Electronics       1.0   
24      125       C-22            Mouse Pad  Electronics       1.0   

         Price   OrderDate  Rating              Review  TotalAmount  
0    12.500000  2023-01-15     5.0               Great    25.000000  
1     9.000000  2023-02-10     4.0               Comfy    27.000000  
2   120.000000  2023-06-05     5.0  No review provided   120.000000  
3     4.500000  2023-04-20     3.0               Skips    22.500000  
4    35.000000  2023-05-12     5.0              Bright    35.000000  
5    14.000000  2023-07-18     5.0               Sweet    14.000000  
6    20.000000  2023-08-22     4.0                Good    20.000000  
7    45.000000  2023-12-01     5.0  No review provided    45.000000  
8    15.000000  2023-11-15     5.0                Fine    15.000000  
9    12.000000  2023-12-05     4.0                Nice    24.000000  
10   10.000000  2024-01-12     5.0              Strong    10.000000  
11    8.500000  2024-02-28     4.0        Staples well     8.500000  
12   18.000000  2024-03-15     5.0               Fresh    36.000000  
13   22.000000  2024-04-01     4.0               Clean    22.000000  
14   15.990000  2024-04-22     5.0           Long life    63.960000  
15    9.500000  2024-05-30     5.0              Smooth     9.500000  
16   24.716957  2024-07-04     3.0              Steady    24.716957  
17   45.000000  2024-08-14     5.0                Warm    45.000000  
18   24.716957  2024-09-19     4.0                None    24.716957  
19    6.500000  2024-10-05     5.0              Simple    13.000000  
20   12.000000  2024-11-11     4.0                Soft    60.000000  
21   18.000000  2024-11-28     2.0                Dark    18.000000  
22   12.000000  2024-12-05     5.0               Green    36.000000  
23   89.000000  2024-12-20     5.0                Loud    89.000000  
24   15.000000  2024-12-30     5.0              Smooth    15.000000

In [138]:
df['DiscountedPrice'] = df['TotalAmount'] - df['TotalAmount']*0.1
df

OrderID CustomerID              Product     Category  Quantity  \
0       101        C-1          Ceramic Mug      Kitchen       2.0   
1       102        C-2         Cotton Socks      Apparel       3.0   
2       103        C-3  Mechanical Keyboard  Electronics       1.0   
3       104        C-1       Ballpoint Pens   Stationery       5.0   
4       105        C-4            Desk Lamp       Office       1.0   
5       106        C-5            Honey Jar       Pantry       1.0   
6       107        C-2             Yoga Mat      Fitness       1.0   
7       108        C-6            USB-C Hub  Electronics       1.0   
8       109        C-7         Water Bottle   Housewares       1.0   
9       110        C-8       Scented Candle         Home       2.0   
10      111        C-9             Tote Bag  Accessories       1.0   
11      112       C-10              Stapler       Office       1.0   
12      113        C-1         Coffee Beans       Pantry       2.0   
13      114       C-11       Desk Organizer       Office       1.0   
14      115       C-12         AA Batteries  Electronics       4.0   
15      116       C-13           Hand Cream       Beauty       1.0   
16      117       C-14          Phone Stand  Electronics       1.0   
17      118       C-15     Oversized Hoodie      Apparel       1.0   
18      119       C-16      27-inch Monitor         None       1.0   
19      120       C-17          Tea Infuser      Kitchen       2.0   
20      121       C-18     Microfiber Cloth   Housewares       5.0   
21      122       C-19           Sunglasses  Accessories       1.0   
22      123       C-20            Succulent         Home       3.0   
23      124       C-21    Bluetooth Speaker  Electronics       1.0   
24      125       C-22            Mouse Pad  Electronics       1.0   

         Price   OrderDate  Rating              Review  TotalAmount  \
0    12.500000  2023-01-15     5.0               Great    25.000000   
1     9.000000  2023-02-10     4.0               Comfy    27.000000   
2   120.000000  2023-06-05     5.0  No review provided   120.000000   
3     4.500000  2023-04-20     3.0               Skips    22.500000   
4    35.000000  2023-05-12     5.0              Bright    35.000000   
5    14.000000  2023-07-18     5.0               Sweet    14.000000   
6    20.000000  2023-08-22     4.0                Good    20.000000   
7    45.000000  2023-12-01     5.0  No review provided    45.000000   
8    15.000000  2023-11-15     5.0                Fine    15.000000   
9    12.000000  2023-12-05     4.0                Nice    24.000000   
10   10.000000  2024-01-12     5.0              Strong    10.000000   
11    8.500000  2024-02-28     4.0        Staples well     8.500000   
12   18.000000  2024-03-15     5.0               Fresh    36.000000   
13   22.000000  2024-04-01     4.0               Clean    22.000000   
14   15.990000  2024-04-22     5.0           Long life    63.960000   
15    9.500000  2024-05-30     5.0              Smooth     9.500000   
16   24.716957  2024-07-04     3.0              Steady    24.716957   
17   45.000000  2024-08-14     5.0                Warm    45.000000   
18   24.716957  2024-09-19     4.0                None    24.716957   
19    6.500000  2024-10-05     5.0              Simple    13.000000   
20   12.000000  2024-11-11     4.0                Soft    60.000000   
21   18.000000  2024-11-28     2.0                Dark    18.000000   
22   12.000000  2024-12-05     5.0               Green    36.000000   
23   89.000000  2024-12-20     5.0                Loud    89.000000   
24   15.000000  2024-12-30     5.0              Smooth    15.000000   

    DiscountedPrice  
0         22.500000  
1         24.300000  
2        108.000000  
3         20.250000  
4         31.500000  
5         12.600000  
6         18.000000  
7         40.500000  
8         13.500000  
9         21.600000  
10         9.000000  
11         7.650000  
12        32.400000  
13        19.800000  
14    

In [139]:
df_more_than_150 = df[df['TotalAmount']>25]
df_more_than_150

OrderID CustomerID              Product     Category  Quantity   Price  \
1       102        C-2         Cotton Socks      Apparel       3.0    9.00   
2       103        C-3  Mechanical Keyboard  Electronics       1.0  120.00   
4       105        C-4            Desk Lamp       Office       1.0   35.00   
7       108        C-6            USB-C Hub  Electronics       1.0   45.00   
12      113        C-1         Coffee Beans       Pantry       2.0   18.00   
14      115       C-12         AA Batteries  Electronics       4.0   15.99   
17      118       C-15     Oversized Hoodie      Apparel       1.0   45.00   
20      121       C-18     Microfiber Cloth   Housewares       5.0   12.00   
22      123       C-20            Succulent         Home       3.0   12.00   
23      124       C-21    Bluetooth Speaker  Electronics       1.0   89.00   

     OrderDate  Rating              Review  TotalAmount  DiscountedPrice  
1   2023-02-10     4.0               Comfy        27.00           24.300  
2   2023-06-05     5.0  No review provided       120.00          108.000  
4   2023-05-12     5.0              Bright        35.00           31.500  
7   2023-12-01     5.0  No review provided        45.00           40.500  
12  2024-03-15     5.0               Fresh        36.00           32.400  
14  2024-04-22     5.0           Long life        63.96           57.564  
17  2024-08-14     5.0                Warm        45.00           40.500  
20  2024-11-11     4.0                Soft        60.00           54.000  
22  2024-12-05     5.0               Green        36.00           32.400  
23  2024-12-20     5.0                Loud        89.00           80.100

In [140]:
# Q5: Select only the columns: Product, Category, TotalAmount, and Rating
# Filter and display all orders from the 'Electronics' category with Rating >= 4

electronics_high_rated = df[(df['Category'] == 'Electronics') & (df['Rating'] >= 4)]

result = electronics_high_rated[['Product', 'Category', 'TotalAmount', 'Rating']]

result

Product     Category  TotalAmount  Rating
2   Mechanical Keyboard  Electronics       120.00     5.0
7             USB-C Hub  Electronics        45.00     5.0
14         AA Batteries  Electronics        63.96     5.0
23    Bluetooth Speaker  Electronics        89.00     5.0
24            Mouse Pad  Electronics        15.00     5.0

In [141]:
# Q6: Use boolean indexing to find all orders where:
# - Quantity > 2 AND Price < 50 OR Rating == 5
# Display the count of such orders
istrue = ((df['Quantity'] > 2) & (df['Price'] < 50)) | (df['Rating'] == 5)
df[istrue]

OrderID CustomerID              Product     Category  Quantity   Price  \
0       101        C-1          Ceramic Mug      Kitchen       2.0   12.50   
1       102        C-2         Cotton Socks      Apparel       3.0    9.00   
2       103        C-3  Mechanical Keyboard  Electronics       1.0  120.00   
3       104        C-1       Ballpoint Pens   Stationery       5.0    4.50   
4       105        C-4            Desk Lamp       Office       1.0   35.00   
5       106        C-5            Honey Jar       Pantry       1.0   14.00   
7       108        C-6            USB-C Hub  Electronics       1.0   45.00   
8       109        C-7         Water Bottle   Housewares       1.0   15.00   
10      111        C-9             Tote Bag  Accessories       1.0   10.00   
12      113        C-1         Coffee Beans       Pantry       2.0   18.00   
14      115       C-12         AA Batteries  Electronics       4.0   15.99   
15      116       C-13           Hand Cream       Beauty       1.0    9.50   
17      118       C-15     Oversized Hoodie      Apparel       1.0   45.00   
19      120       C-17          Tea Infuser      Kitchen       2.0    6.50   
20      121       C-18     Microfiber Cloth   Housewares       5.0   12.00   
22      123       C-20            Succulent         Home       3.0   12.00   
23      124       C-21    Bluetooth Speaker  Electronics       1.0   89.00   
24      125       C-22            Mouse Pad  Electronics       1.0   15.00   

     OrderDate  Rating              Review  TotalAmount  DiscountedPrice  
0   2023-01-15     5.0               Great        25.00           22.500  
1   2023-02-10     4.0               Comfy        27.00           24.300  
2   2023-06-05     5.0  No review provided       120.00          108.000  
3   2023-04-20     3.0               Skips        22.50           20.250  
4   2023-05-12     5.0              Bright        35.00           31.500  
5   2023-07-18     5.0               Sweet        14.00           12.600  
7   2023-12-01     5.0  No review provided        45.00           40.500  
8   2023-11-15     5.0                Fine        15.00           13.500  
10  2024-01-12     5.0              Strong        10.00            9.000  
12  2024-03-15     5.0               Fresh        36.00           32.400  
14  2024-04-22     5.0           Long life        63.96           57.564  
15  2024-05-30     5.0              Smooth         9.50            8.550  
17  2024-08-14     5.0                Warm        45.00           40.500  
19  2024-10-05     5.0              Simple        13.00           11.700  
20  2024-11-11     4.0                Soft        60.00           54.000  
22  2024-12-05     5.0               Green        36.00           32.400  
23  2024-12-20     5.0                Loud        89.00           80.100  
24  2024-12-30     5.0              Smooth        15.00           13.500

In [142]:
print(f"Total Count: {len(df[istrue])}")

Total Count: 18


In [143]:
# Q7: Sort the entire DataFrame by OrderDate (descending) and then by TotalAmount (descending)
# Create a new column 'SalesRank' that ranks products by TotalAmount in descending order

df_sorted = df.sort_values(by = ['OrderDate', 'TotalAmount'] , ascending = [False, False])
df_sorted

OrderID CustomerID              Product     Category  Quantity  \
24      125       C-22            Mouse Pad  Electronics       1.0   
23      124       C-21    Bluetooth Speaker  Electronics       1.0   
22      123       C-20            Succulent         Home       3.0   
21      122       C-19           Sunglasses  Accessories       1.0   
20      121       C-18     Microfiber Cloth   Housewares       5.0   
19      120       C-17          Tea Infuser      Kitchen       2.0   
18      119       C-16      27-inch Monitor         None       1.0   
17      118       C-15     Oversized Hoodie      Apparel       1.0   
16      117       C-14          Phone Stand  Electronics       1.0   
15      116       C-13           Hand Cream       Beauty       1.0   
14      115       C-12         AA Batteries  Electronics       4.0   
13      114       C-11       Desk Organizer       Office       1.0   
12      113        C-1         Coffee Beans       Pantry       2.0   
11      112       C-10              Stapler       Office       1.0   
10      111        C-9             Tote Bag  Accessories       1.0   
9       110        C-8       Scented Candle         Home       2.0   
7       108        C-6            USB-C Hub  Electronics       1.0   
8       109        C-7         Water Bottle   Housewares       1.0   
6       107        C-2             Yoga Mat      Fitness       1.0   
5       106        C-5            Honey Jar       Pantry       1.0   
2       103        C-3  Mechanical Keyboard  Electronics       1.0   
4       105        C-4            Desk Lamp       Office       1.0   
3       104        C-1       Ballpoint Pens   Stationery       5.0   
1       102        C-2         Cotton Socks      Apparel       3.0   
0       101        C-1          Ceramic Mug      Kitchen       2.0   

         Price   OrderDate  Rating              Review  TotalAmount  \
24   15.000000  2024-12-30     5.0              Smooth    15.000000   
23   89.000000  2024-12-20     5.0                Loud    89.000000   
22   12.000000  2024-12-05     5.0               Green    36.000000   
21   18.000000  2024-11-28     2.0                Dark    18.000000   
20   12.000000  2024-11-11     4.0                Soft    60.000000   
19    6.500000  2024-10-05     5.0              Simple    13.000000   
18   24.716957  2024-09-19     4.0                None    24.716957   
17   45.000000  2024-08-14     5.0                Warm    45.000000   
16   24.716957  2024-07-04     3.0              Steady    24.716957   
15    9.500000  2024-05-30     5.0              Smooth     9.500000   
14   15.990000  2024-04-22     5.0           Long life    63.960000   
13   22.000000  2024-04-01     4.0               Clean    22.000000   
12   18.000000  2024-03-15     5.0               Fresh    36.000000   
11    8.500000  2024-02-28     4.0        Staples well     8.500000   
10   10.000000  2024-01-12     5.0              Strong    10.000000   
9    12.000000  2023-12-05     4.0                Nice    24.000000   
7    45.000000  2023-12-01     5.0  No review provided    45.000000   
8    15.000000  2023-11-15     5.0                Fine    15.000000   
6    20.000000  2023-08-22     4.0                Good    20.000000   
5    14.000000  2023-07-18     5.0               Sweet    14.000000   
2   120.000000  2023-06-05     5.0  No review provided   120.000000   
4    35.000000  2023-05-12     5.0              Bright    35.000000   
3     4.500000  2023-04-20     3.0               Skips    22.500000   
1     9.000000  2023-02-10     4.0               Comfy    27.000000   
0    12.500000  2023-01-15     5.0               Great    25.000000   

    DiscountedPrice  
24        13.500000  
23        80.100000  
22        32.400000  
21        16.200000  
20        54.000000  
19        11.700000  
18        22.245261  
17        40.500000  
16        22.245261  
15         8.550000  
14        57.564000  
13        19.800000  
12        32.400000  
11         7.650000  
10    

In [144]:
df['SalesRank'] = df['TotalAmount'].rank(ascending=True)
df

OrderID CustomerID              Product     Category  Quantity  \
0       101        C-1          Ceramic Mug      Kitchen       2.0   
1       102        C-2         Cotton Socks      Apparel       3.0   
2       103        C-3  Mechanical Keyboard  Electronics       1.0   
3       104        C-1       Ballpoint Pens   Stationery       5.0   
4       105        C-4            Desk Lamp       Office       1.0   
5       106        C-5            Honey Jar       Pantry       1.0   
6       107        C-2             Yoga Mat      Fitness       1.0   
7       108        C-6            USB-C Hub  Electronics       1.0   
8       109        C-7         Water Bottle   Housewares       1.0   
9       110        C-8       Scented Candle         Home       2.0   
10      111        C-9             Tote Bag  Accessories       1.0   
11      112       C-10              Stapler       Office       1.0   
12      113        C-1         Coffee Beans       Pantry       2.0   
13      114       C-11       Desk Organizer       Office       1.0   
14      115       C-12         AA Batteries  Electronics       4.0   
15      116       C-13           Hand Cream       Beauty       1.0   
16      117       C-14          Phone Stand  Electronics       1.0   
17      118       C-15     Oversized Hoodie      Apparel       1.0   
18      119       C-16      27-inch Monitor         None       1.0   
19      120       C-17          Tea Infuser      Kitchen       2.0   
20      121       C-18     Microfiber Cloth   Housewares       5.0   
21      122       C-19           Sunglasses  Accessories       1.0   
22      123       C-20            Succulent         Home       3.0   
23      124       C-21    Bluetooth Speaker  Electronics       1.0   
24      125       C-22            Mouse Pad  Electronics       1.0   

         Price   OrderDate  Rating              Review  TotalAmount  \
0    12.500000  2023-01-15     5.0               Great    25.000000   
1     9.000000  2023-02-10     4.0               Comfy    27.000000   
2   120.000000  2023-06-05     5.0  No review provided   120.000000   
3     4.500000  2023-04-20     3.0               Skips    22.500000   
4    35.000000  2023-05-12     5.0              Bright    35.000000   
5    14.000000  2023-07-18     5.0               Sweet    14.000000   
6    20.000000  2023-08-22     4.0                Good    20.000000   
7    45.000000  2023-12-01     5.0  No review provided    45.000000   
8    15.000000  2023-11-15     5.0                Fine    15.000000   
9    12.000000  2023-12-05     4.0                Nice    24.000000   
10   10.000000  2024-01-12     5.0              Strong    10.000000   
11    8.500000  2024-02-28     4.0        Staples well     8.500000   
12   18.000000  2024-03-15     5.0               Fresh    36.000000   
13   22.000000  2024-04-01     4.0               Clean    22.000000   
14   15.990000  2024-04-22     5.0           Long life    63.960000   
15    9.500000  2024-05-30     5.0              Smooth     9.500000   
16   24.716957  2024-07-04     3.0              Steady    24.716957   
17   45.000000  2024-08-14     5.0                Warm    45.000000   
18   24.716957  2024-09-19     4.0                None    24.716957   
19    6.500000  2024-10-05     5.0              Simple    13.000000   
20   12.000000  2024-11-11     4.0                Soft    60.000000   
21   18.000000  2024-11-28     2.0                Dark    18.000000   
22   12.000000  2024-12-05     5.0               Green    36.000000   
23   89.000000  2024-12-20     5.0                Loud    89.000000   
24   15.000000  2024-12-30     5.0              Smooth    15.000000   

    DiscountedPrice  SalesRank  
0         22.500000       15.0  
1         24.300000       16.0  
2        108.000000       25.0  
3         20.250000       11.0  
4         31.500000       17.0  
5         12.600000        5.0  
6         18.000000        9.0  
7         40.500000       20.5  
8         13.500000        6.5  
9     

In [145]:
# Q8: Find the top 5 best-selling products based on total quantity sold
# Display the product name and total quantity in descending order

df_sorted = df.sort_values(by = ['Quantity'], ascending = False)
df_sorted.head(5)

OrderID CustomerID           Product     Category  Quantity  Price  \
3       104        C-1    Ballpoint Pens   Stationery       5.0   4.50   
20      121       C-18  Microfiber Cloth   Housewares       5.0  12.00   
14      115       C-12      AA Batteries  Electronics       4.0  15.99   
1       102        C-2      Cotton Socks      Apparel       3.0   9.00   
22      123       C-20         Succulent         Home       3.0  12.00   

     OrderDate  Rating     Review  TotalAmount  DiscountedPrice  SalesRank  
3   2023-04-20     3.0      Skips        22.50           20.250       11.0  
20  2024-11-11     4.0       Soft        60.00           54.000       22.0  
14  2024-04-22     5.0  Long life        63.96           57.564       23.0  
1   2023-02-10     4.0      Comfy        27.00           24.300       16.0  
22  2024-12-05     5.0      Green        36.00           32.400       18.5

In [146]:
df_sorted = df.sort_values(by = ['Quantity'], ascending = False)
df_sorted[['Product', 'Quantity']]

Product  Quantity
3        Ballpoint Pens       5.0
20     Microfiber Cloth       5.0
14         AA Batteries       4.0
1          Cotton Socks       3.0
22            Succulent       3.0
9        Scented Candle       2.0
0           Ceramic Mug       2.0
19          Tea Infuser       2.0
12         Coffee Beans       2.0
8          Water Bottle       1.0
7             USB-C Hub       1.0
6              Yoga Mat       1.0
5             Honey Jar       1.0
4             Desk Lamp       1.0
2   Mechanical Keyboard       1.0
11              Stapler       1.0
10             Tote Bag       1.0
16          Phone Stand       1.0
15           Hand Cream       1.0
13       Desk Organizer       1.0
18      27-inch Monitor       1.0
17     Oversized Hoodie       1.0
21           Sunglasses       1.0
23    Bluetooth Speaker       1.0
24            Mouse Pad       1.0

In [147]:
# Q9: Group the data by 'Category' and calculate:
# - Total sales (sum of TotalAmount)
# - Average rating
# - Number of orders
# Display the results sorted by total sales

g_df = df.groupby('Category')['TotalAmount'].sum()
print(g_df)

Category
Accessories     28.000000
Apparel         72.000000
Beauty           9.500000
Electronics    357.676957
Fitness         20.000000
Home            60.000000
Housewares      75.000000
Kitchen         38.000000
Office          65.500000
Pantry          50.000000
Stationery      22.500000
Name: TotalAmount, dtype: float64


In [148]:
g_df1 = df.groupby('Category')['Rating'].mean()
print(g_df1)

Category
Accessories    3.500000
Apparel        4.500000
Beauty         5.000000
Electronics    4.666667
Fitness        4.000000
Home           4.500000
Housewares     4.500000
Kitchen        5.000000
Office         4.333333
Pantry         5.000000
Stationery     3.000000
Name: Rating, dtype: float64


In [149]:
g_df2 = df.groupby('Category')['Quantity'].sum()
print(g_df2)

Category
Accessories    2.0
Apparel        4.0
Beauty         1.0
Electronics    9.0
Fitness        1.0
Home           5.0
Housewares     6.0
Kitchen        4.0
Office         3.0
Pantry         3.0
Stationery     5.0
Name: Quantity, dtype: float64


In [150]:
g_df.sort_values(ascending = False)

Category
Electronics    357.676957
Housewares      75.000000
Apparel         72.000000
Office          65.500000
Home            60.000000
Pantry          50.000000
Kitchen         38.000000
Accessories     28.000000
Stationery      22.500000
Fitness         20.000000
Beauty           9.500000
Name: TotalAmount, dtype: float64

In [152]:
# Q10: Create a pivot table showing average Price for each Category and Rating combination
# Use groupby with multiple columns (Category, Product) and aggregate multiple functions
# Create Pivot Table


In [158]:
# Q11: Convert the Quantity and Price columns to NumPy arrays
# Create a 2D array combining these two columns
# Display array properties: shape, dtype, ndim, size

quantity_arr = df['Quantity'].to_numpy()
price_arr = df['Price'].to_numpy()

combined_2d = np.array([quantity_arr, price_arr]).T

print("Shape: ", quantity_arr.shape)
print("Dtype: ", quantity_arr.dtype)
print("Ndim: ", quantity_arr.ndim)
print("Size: ", quantity_arr.size)



Shape:  (25,)
Dtype:  float64
Ndim:  1
Size:  25


In [166]:
# Q12: Create a 1D NumPy array of 100 random prices between 10 and 500
# Calculate mean, median, standard deviation, min, and max using NumPy functions
# Reshape this array into a 10x10 matrix
arr = np.random.uniform(10, 500, 100)
arr = np.round(arr, 2)

print("Mean: ",np.mean(arr))
print("Median: ", np.median(arr))
print("Standard Deviation: ", np.std(arr))
print("Min: ", np.min(arr))
print("Max: ", np.max(arr))

Mean:  248.74379999999996
Median:  240.51
Standard Deviation:  154.2576968762337
Min:  18.87
Max:  497.26


In [167]:
arr.reshape(10, 10)

array([[462.86, 294.87, 497.26, 439.67, 172.  ,  54.19, 481.31, 149.47,
        485.93, 361.73],
       [308.86, 428.32, 417.75, 463.1 , 150.14, 402.25, 374.07,  20.31,
         64.99, 297.88],
       [205.08, 123.12, 388.02, 100.4 , 322.34, 445.22,  40.73, 382.26,
         55.02, 489.05],
       [268.43,  60.76, 481.06, 294.87,  41.2 , 226.3 ,  71.47,  88.81,
        381.01, 195.42],
       [490.92,  77.24, 364.26, 458.5 , 479.44, 441.96,  18.87, 116.65,
        439.27, 108.83],
       [182.01, 248.72, 134.57, 234.56, 237.93, 277.48, 345.59, 288.15,
        430.23, 246.12],
       [412.88, 375.92, 108.68, 458.75, 344.05, 405.9 , 128.03, 106.7 ,
        193.97, 378.85],
       [ 59.56, 148.74,  28.94, 399.15,  93.93, 424.86, 134.8 , 401.95,
        229.77,  29.45],
       [ 72.3 ,  18.96, 345.78,  79.87, 243.09, 370.55,  43.73, 157.03,
        105.27,  40.4 ],
       [118.65, 220.31,  22.2 ,  83.05, 343.48, 336.67, 436.2 ,  66.61,
         88.01, 208.51]])

In [175]:
# Q13: Create two 3D NumPy arrays (3x3x3) with random integers
# Perform element-wise addition, multiplication, and matrix multiplication
# Use boolean indexing to filter values greater than 50

arr3D_1 = np.random.randint(10, 50, size = (3, 3))
arr3D_2 = np.random.randint(10, 50, size = (3, 3))

print("Addition: ",arr3D_1 + arr3D_2)
print("Multiplication: ",arr3D_1 * arr3D_2)
print("Matrix Multiplication: ",np.dot(arr3D_1,arr3D_2))

Addition:  [[83 91 65]
 [55 57 47]
 [35 49 71]]
Multiplication:  [[1692 2070  816]
 [ 754  506  496]
 [ 306  588 1128]]
Matrix Multiplication:  [[3194 3097 4090]
 [2528 2259 3202]
 [2004 2312 2595]]


In [176]:
# Q14: Create NumPy arrays using special values:
# - Array of zeros (5x5)
# - Array of ones (3x4)
# - Identity matrix (4x4)
# - Array with values from 0 to 50 with step of 5 using arange
# Concatenate and stack these arrays

zeros_arr = np.zeros((5, 5))
ones_arr = np.ones((3, 4))
identity_matrix = np.eye(4)
arr = np.arange(0, 51, 5)
print("Zeros Array: ", zeros_arr)
print("Ones Array: ", ones_arr)
print("Identity matrix: ", identity_matrix)
print("Arr: ", arr)

Zeros Array:  [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Ones Array:  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Identity matrix:  [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Arr:  [ 0  5 10 15 20 25 30 35 40 45 50]
